# Generated by Django 5.2.13 on 2026-04-23 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cover_art', models.ImageField(upload_to='covers/%Y/%m/')),
                ('accent_color', models.CharField(default='#6366f1', help_text='Hex color for the landing template (e.g. #7c3aed).', max_length=7)),
                ('spotify_url', models.URLField(blank=True)),
                ('apple_music_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tidal_url', models.URLField(blank=True)),
                ('soundcloud_url', models.URLField(blank=True)),
                ('bandcamp_url', models.URLField(blank=True)),
                ('amazon_music_url', models.URLField(blank=True)),
                ('deezer_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('preferred_platform', models.CharField(choices=[('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('youtube', 'YouTube'), ('tidal', 'Tidal'), ('soundcloud', 'SoundCloud'), ('bandcamp', 'Bandcamp'), ('amazon_music', 'Amazon Music'), ('deezer', 'Deezer')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_time_fans', to='smartlinks.song')),
            ],
            options={
                'db_table': 'fans',
            },
        ),
        migrations.CreateModel(
            name='OutboundLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('youtube', 'YouTube'), ('tidal', 'Tidal'), ('soundcloud', 'SoundCloud'), ('bandcamp', 'Bandcamp'), ('amazon_music', 'Amazon Music'), ('deezer', 'Deezer')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_clicks', to='smartlinks.fan')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_clicks', to='smartlinks.song')),
            ],
            options={
                'db_table': 'analytics_outbound_link_clicks',
                'indexes': [models.Index(fields=['song', 'created_at'], name='analytics_o_song_id_1b4f84_idx'), models.Index(fields=['song', 'platform'], name='analytics_o_song_id_974a14_idx')],
            },
        ),
        migrations.CreateModel(
            name='LandingPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('referrer', models.CharField(blank=True, max_length=512)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_views', to='smartlinks.song')),
            ],
            options={
                'db_table': 'analytics_landing_page_views',
                'indexes': [models.Index(fields=['song', 'created_at'], name='analytics_l_song_id_6b8201_idx')],
            },
        ),
        migrations.CreateModel(
            name='FanGateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_submissions', to='smartlinks.song')),
            ],
            options={
                'db_table': 'analytics_fan_gate_submissions',
                'indexes': [models.Index(fields=['song', 'created_at'], name='analytics_f_song_id_282f86_idx')],
            },
        ),
    ]
