# Generated by Django 5.2.13 on 2026-04-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='distribution_source_url',
            field=models.URLField(blank=True, help_text='Last smart-link / distro page you imported from (set automatically).', max_length=2048),
        ),
        migrations.AddField(
            model_name='song',
            name='import_from_smart_link',
            field=models.URLField(blank=True, help_text='One-time: paste a distro / presave smart link, save the song, and we pull streaming URLs from that page into the fields above (then clear this).', max_length=2048),
        ),
    ]
