# Generated by Django 5.2.13 on 2026-04-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlinks', '0002_song_distribution_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='amazon_music_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='song',
            name='apple_music_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='song',
            name='bandcamp_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='song',
            name='deezer_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='song',
            name='soundcloud_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='song',
            name='tidal_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
