# Generated by Django 5.2.13 on 2026-04-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlinks', '0003_lengthen_song_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(blank=True, help_text='Listener-facing link only: open.spotify.com, spotify.link, or your public presave URL. Do not paste accounts.spotify.com login / OAuth URLs.', max_length=2048),
        ),
    ]
