# Generated by Django 5.2.13 on 2026-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlinks', '0004_spotify_url_listener_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(blank=True, help_text='Spotify presave / listen link — e.g. Toolost or Feature.fm smart URL (api.ffm.to/…), or open.spotify.com / spotify.link when you have them.', max_length=2048),
        ),
    ]
