# Generated by Django 5.2.13 on 2026-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlinks', '0005_spotify_url_ffm_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='amazon_music_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='apple_music_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='bandcamp_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='deezer_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='distribution_source_url',
            field=models.TextField(blank=True, help_text='Last smart-link / distro page you imported from (set automatically).'),
        ),
        migrations.AlterField(
            model_name='song',
            name='import_from_smart_link',
            field=models.TextField(blank=True, help_text='One-time: paste a distro / presave smart link, save the song, and we pull streaming URLs from that page into the fields above (then clear this).'),
        ),
        migrations.AlterField(
            model_name='song',
            name='soundcloud_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_url',
            field=models.TextField(blank=True, help_text='Spotify presave / listen link — e.g. Toolost or Feature.fm smart URL (api.ffm.to/…), or open.spotify.com / spotify.link when you have them.'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tidal_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.TextField(blank=True),
        ),
    ]
