# Generated by Django 5.2.13 on 2026-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartlinks", "0007_song_release_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="landing_template",
            field=models.CharField(
                choices=[("modern", "Modern"), ("minimal", "Minimal")],
                default="modern",
                help_text="Choose which smart-link layout to render for this song.",
                max_length=16,
            ),
        ),
    ]
